# Generated by Django 5.1 on 2024-11-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_empleado_jefatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nro_pedido',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
