# Generated by Django 5.1 on 2024-11-23 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pedido_nro_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='precio_total',
        ),
    ]
