# Generated by Django 3.2.25 on 2024-11-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merma_detallemerma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merma',
            name='empleado',
        ),
    ]
